version: '3.8'

services:
  vectradb:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DB_PATH=/data/vectra.db
      - LOG_LEVEL=info
      - LOG_FORMAT=json
    volumes:
      - ./data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add a reverse proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./deployments/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - vectradb
    restart: unless-stopped

volumes:
  data:
